### ISSUE TITLE
Allow to pass layer config via CLI argument

### ISSUE THREAD

**Issue by thomas-maschler** [wri/gfw_pixetl#8]
**Is your feature request related to a problem? Please describe.**
We currently need to first write to the layer config file in order to define the tile pipeline. It would be more flexible to allow users to pass config specifications via CLI arguments

**Describe the solution you'd like**
Allow to pass layer config via CLI arguments. This could be either a dict or a link to a yaml file containing the layer specifications.

**Comment by dmannarino** [comment]
Done!
